# Generated by Django 5.2.9 on 2026-02-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blockusermodel_usercontactsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactsmodel',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
