# Generated by Django 5.2.9 on 2026-02-20 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usercontactsmodel_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettingsmodel',
            name='timizone',
            field=models.CharField(default=django.utils.timezone.now),
        ),
    ]
