# Generated by Django 5.2.9 on 2026-02-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usersettingsmodel_timizone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockusermodel',
            name='blocked_calls',
        ),
        migrations.RemoveField(
            model_name='blockusermodel',
            name='blocked_message',
        ),
        migrations.RemoveField(
            model_name='userprivatymodel',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='usersettingsmodel',
            name='timizone',
        ),
    ]
