# Generated by Django 6.0.3 on 2026-03-17 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0009_alter_chatmembersmodel_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'messages_type',
            },
        ),
        migrations.CreateModel(
            name='MessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_delited', models.BooleanField(default=False)),
                ('is_pined', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chatmodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messages.messagestypemodel')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageReplaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_sent', to='messages.messagesmodel')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_received', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'message_replays',
            },
        ),
        migrations.CreateModel(
            name='MessageReactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to='chats.chatmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'message_reaction',
            },
        ),
        migrations.CreateModel(
            name='MessageMetadataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=250)),
                ('file_size', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'message_metadata',
            },
        ),
        migrations.CreateModel(
            name='MessageLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'message_link',
            },
        ),
        migrations.CreateModel(
            name='MessageHashtagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('normalized_hashtag', models.CharField(max_length=100)),
                ('position_start', models.IntegerField()),
                ('position_end', models.IntegerField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'message_hashtag',
            },
        ),
        migrations.CreateModel(
            name='MessageForwardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_at', models.DateTimeField(auto_now_add=True)),
                ('forward_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_forwards', to=settings.AUTH_USER_MODEL)),
                ('original_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_forwards', to='chats.chatmodel')),
                ('original_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_forwards', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'message_forward',
            },
        ),
        migrations.CreateModel(
            name='MessageEditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_message', models.TextField()),
                ('new_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='messages.messagesmodel')),
            ],
            options={
                'db_table': 'messages_edit',
            },
        ),
        migrations.CreateModel(
            name='MessageStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='messages.messagesmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_status',
            },
        ),
    ]
