# Generated by Django 6.0.3 on 2026-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagereplaysmodel',
            old_name='mmessage',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='messagestypemodel',
            name='code',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='TEXT', max_length=20),
        ),
    ]
