# Generated by Django 6.0.3 on 2026-05-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0002_initial'),
        ('messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageeditmodel',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageforwardmodel',
            name='forward_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereactionmodel',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to='chats.chatmodel'),
        ),
        migrations.AddField(
            model_name='messagereactionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chatmodel'),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereplaysmodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_sent', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagereplaysmodel',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_received', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagereactionmodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagemetadatamodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagelinkmodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagehashtagmodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messageforwardmodel',
            name='forwarded_message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forward_info', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messageforwardmodel',
            name='original_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_forwards', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messageeditmodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagestatusmodel',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='messagestatusmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messages.messagestypemodel'),
        ),
    ]
