# Generated by Django 6.0.3 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_rename_mmessage_messagereplaysmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestypemodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
