# Generated by Django 6.0.3 on 2026-05-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messages.messagesmodel'),
        ),
    ]
