# Generated by Django 6.0.3 on 2026-05-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0003_messagesmodel_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereactionmodel',
            name='chat',
        ),
        migrations.DeleteModel(
            name='MessageReplaysModel',
        ),
    ]
