# Generated by Django 6.0.3 on 2026-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0003_alter_messagestypemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestypemodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
