# Generated by Django 6.0.3 on 2026-05-13 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0004_remove_messagereactionmodel_chat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereactionmodel',
            unique_together={('user', 'message')},
        ),
    ]
