# Generated by Django 6.0.3 on 2026-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0004_alter_messagestypemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestypemodel',
            name='code',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('VIDEO', 'Video')], default='TEXT', max_length=20),
        ),
    ]
