# Generated by Django 5.2.9 on 2026-03-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMembersRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=20)),
                ('able_to_invite', models.BooleanField(default=True)),
                ('able_to_delete', models.BooleanField(default=True)),
                ('able_to_message', models.BooleanField(default=True)),
                ('able_to_update', models.BooleanField(default=True)),
                ('able_to_pin', models.BooleanField(default=True)),
                ('able_to_edit_chat', models.BooleanField(default=True)),
                ('able_to_ban', models.BooleanField(default=True)),
                ('able_to_manage', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'members_role',
            },
        ),
        migrations.CreateModel(
            name='ChatTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('channel', 'Channel')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('is_edit_message', models.BooleanField(default=True)),
                ('is_delete_message', models.BooleanField(default=True)),
                ('is_add_members', models.BooleanField(default=True)),
                ('is_add_message', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_types',
            },
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL)),
                ('chat_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chattypesmodel')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatMembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatmembersrolemodel')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatmodel')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
