# Generated by Django 6.0.3 on 2026-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBannedUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=100)),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent'), ('mute', 'Mute')], max_length=40)),
                ('expired_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_banned',
            },
        ),
        migrations.CreateModel(
            name='ChatInvitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_url', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chat_invitation',
            },
        ),
        migrations.CreateModel(
            name='ChatMembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='ChatMembersRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('able_to_invite', models.BooleanField(default=False)),
                ('able_to_delete', models.BooleanField(default=False)),
                ('able_to_message', models.BooleanField(default=True)),
                ('able_to_update', models.BooleanField(default=False)),
                ('able_to_pin', models.BooleanField(default=False)),
                ('able_to_edit_chat', models.BooleanField(default=False)),
                ('able_to_ban', models.BooleanField(default=False)),
                ('able_to_manage', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'members_role',
            },
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_members', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'chat_settings',
            },
        ),
        migrations.CreateModel(
            name='ChatTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('channel', 'Channel')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_edit_message', models.BooleanField(default=True)),
                ('is_delete_message', models.BooleanField(default=True)),
                ('is_add_members', models.BooleanField(default=True)),
                ('is_add_message', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_types',
            },
        ),
    ]
