# Generated by Django 5.2.9 on 2026-03-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='chat_type_id',
            new_name='chat_type',
        ),
    ]
