# Generated by Django 6.0.3 on 2026-05-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbannedusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmembersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatinvitationmodel',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitation', to='chats.chatmembersmodel'),
        ),
        migrations.AddField(
            model_name='chatbannedusermodel',
            name='banned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_by_user', to='chats.chatmembersmodel'),
        ),
        migrations.AddField(
            model_name='chatmembersmodel',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatmembersrolemodel'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_for_chats', to='messages.messagesmodel'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmembersmodel',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatmodel'),
        ),
        migrations.AddField(
            model_name='chatinvitationmodel',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='chats.chatmodel'),
        ),
        migrations.AddField(
            model_name='chatbannedusermodel',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to='chats.chatmodel'),
        ),
        migrations.AddField(
            model_name='chatsettingsmodel',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='chats.chatmodel'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='chat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chattypesmodel'),
        ),
    ]
