# Generated by Django 5.2.9 on 2026-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_chat_type_id_chatmodel_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
