# Generated by Django 5.2.9 on 2026-03-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatmodel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBannedUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=100)),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent'), ('mute', 'Mute')], max_length=40)),
                ('expired_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_by_user', to='chats.chatmembersmodel')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to='chats.chatmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_banned',
            },
        ),
        migrations.CreateModel(
            name='ChatInvitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_url', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=100)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='chats.chatmodel')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitation', to='chats.chatmembersmodel')),
            ],
            options={
                'db_table': 'chat_invitation',
            },
        ),
        migrations.CreateModel(
            name='ChatSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_members', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(max_length=250)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='chats.chatmodel')),
            ],
            options={
                'db_table': 'chat_settings',
            },
        ),
    ]
