# Generated by Django 5.2.9 on 2026-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatbannedusermodel_chatinvitationmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_edit_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_manage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
