# Generated by Django 5.2.9 on 2026-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chatmembersrolemodel_able_to_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattypesmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
