# Generated by Django 5.2.9 on 2026-03-07 15:51

from django.db import migrations


def create_chat_types(apps, schema_editor):
    ChatTypesModel = apps.get_model("chats", "ChatTypesModel")
    types = [
        ("direct", "Direct"),
        ("group", "Group"),
        ("channel", "Channel"),
    ]
    for name, description in types:
        ChatTypesModel.objects.get_or_create(
            name=name,
            defaults={"description": description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_alter_chatmembersrolemodel_able_to_ban_and_more"),
    ]

    operations = [
        migrations.RunPython(create_chat_types),
    ]
