# Generated by Django 5.2.9 on 2026-03-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chattypesmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembersrolemodel',
            name='able_to_message',
            field=models.BooleanField(default=True),
        ),
    ]
