# Generated by Django 5.2.9 on 2026-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_create_chat_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattypesmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
