# Generated by Django 5.2.9 on 2026-03-09 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chatmembersrolemodel_able_to_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembersmodel',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatmembersrolemodel'),
        ),
    ]
