# Generated by Django 5.2.9 on 2026-03-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chatmembersmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembersmodel',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='chats.chatmembersrolemodel'),
        ),
    ]
