# Generated by Django 6.0.3 on 2026-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_chatmembersmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(default='tt', max_length=50),
            preserve_default=False,
        ),
    ]
