# Generated by Django 6.0.3 on 2026-04-28 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_chatmodel_name'),
        ('messages', '0002_rename_mmessage_messagereplaysmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_for_chats', to='messages.messagesmodel'),
        ),
    ]
