# Generated by Django 6.0.2 on 2026-02-14 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('verificated_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('is_verificated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_code',
            },
        ),
        migrations.CreateModel(
            name='UserDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=256)),
                ('os', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('web', 'Web')], max_length=25)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_device',
            },
        ),
        migrations.CreateModel(
            name='UserSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(unique=True)),
                ('refresh_token_expire', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('blocked', 'Blocked'), ('logout', 'Logout')], max_length=20)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
    ]
