# Generated by Django 6.0.2 on 2026-02-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeusermodel',
            name='verificated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
