# Generated by Django 5.2.9 on 2026-02-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_alter_codeusermodel_verificated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeusermodel',
            name='is_verificated',
        ),
    ]
